apiVersion: v1
kind: Service
metadata:
  name: postgres-camunda
  labels:
    app: camunda-pasq
spec:
  selector:
    app: camunda-pasq
  clusterIP: None
  ports:
  - port: 5432
    # targetPort: <Target Port>
